plugins {
    id 'java-library'
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

sourceSets {
    main {
        java {
            srcDirs = ['src/main/java']
        }
    }
    test {
        java {
            srcDirs = ['src/test/java']
        }
    }
}

dependencies {
    implementation 'org.apache.lucene:lucene-core:4.7.2'
    implementation 'org.apache.lucene:lucene-analyzers-common:4.7.2'
    implementation 'org.apache.lucene:lucene-queryparser:4.7.2'
    
    implementation 'com.googlecode.json-simple:json-simple:1.1.1'
    implementation 'org.apache.commons:commons-lang3:3.8'
    implementation 'org.slf4j:slf4j-api:1.7.12'
    
    testImplementation 'commons-io:commons-io:2.22.0'
    testImplementation 'commons-codec:commons-codec:1.22.0'
    testImplementation 'junit:junit:4.13.2'
}
